project:
  type: book
  output-dir: docs

book:
  title: "Probabilidad I"
  author: "Matías Pozo"
  date: "17-03-2026"
  chapters:
    - index.qmd
    - clase_1.qmd
    - clase_2.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles/styles.css
  pdf:
    documentclass: scrreprt



